name: Check Version Updated

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pkg-size-report:
    name: Check Version Updated
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4

      - name: Check version updated
        shell: bash
        run: ./.github/scripts/check_version_updated.sh
