name: Lint

on:
  pull_request:
    branches: [master]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Lint
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20.x'

      - name: Install packages
        run: yarn

      - name: Run Markdownlint
        run: npx markdownlint ./

      - name: Run Prettier
        run: npx prettier **/*.{js,json,ts,yml} --check

      - name: Run ESlint
        run: yarn lint
